/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import ConexionBD.Conexion;

/**
 *
 * @author Aaron
 */
public class EditarEstudiante extends javax.swing.JInternalFrame {
 int selec=-1;
    /**
     * Creates new form modificarAlumno
     */
    public EditarEstudiante() {
        initComponents();
        
                        try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
          Statement s = conexion.createStatement(); 
             ResultSet rs = s.executeQuery ("SELECT * FROM `Alumno`");
           DefaultTableModel modelo= new DefaultTableModel();
           talumnos.setModel(modelo);
           modelo.addColumn("Codigo");
           modelo.addColumn("Nombre");
           
             while(rs.next()){
               Object []filas =new Object[2];
               filas[0]=rs.getInt("idAlumno");
               filas[1]=rs.getString("nombre");
               modelo.addRow(filas);
             }
             
             
            
            
            
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        talumnos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Agregar Alumno");
        setPreferredSize(new java.awt.Dimension(500, 340));
        getContentPane().setLayout(null);

        talumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ));
        talumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                talumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(talumnos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 200, 277);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 30, 88, 23);

        jButton3.setText("Refrescar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 60, 88, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/1.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 0, 410, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id= talumnos.getValueAt(selec, 0).toString();
        
        try {
            try{
                Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
          Statement s = conexion.createStatement(); 
         
          
            int executeUpdate = s.executeUpdate ("UPDATE Alumno SET nombre='"+talumnos.getValueAt(selec, 1).toString()+"' WHERE idAlumno="+id);
       
            if(executeUpdate==1){
                javax.swing.JOptionPane.showMessageDialog(null, "Se Actualizo la informacion");
            }else if(executeUpdate==0){
                javax.swing.JOptionPane.showMessageDialog(null, "Error!! no se puedo ingresar la información");
            }
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(EditarMateria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
          Statement s = conexion.createStatement(); 
             ResultSet rs = s.executeQuery ("SELECT * FROM `Alumno`");
           DefaultTableModel modelo= new DefaultTableModel();
           talumnos.setModel(modelo);
           modelo.addColumn("Codigo");
           modelo.addColumn("Nombre");
           
             while(rs.next()){
               Object []filas =new Object[2];
               filas[0]=rs.getInt("idAlumno");
               filas[1]=rs.getString("nombre");
               modelo.addRow(filas);
             }
             
             
            
            
            
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void talumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_talumnosMouseClicked
        // TODO add your handling code here:
           selec=talumnos.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_talumnosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable talumnos;
    // End of variables declaration//GEN-END:variables
}
