/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import ConexionBD.Conexion;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aaron
 */
public class EditarMateria extends javax.swing.JInternalFrame {
    int selec=-1;
    /**
     * Creates new form modificarCurso
     */
    public EditarMateria() {
        initComponents();
                try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
          Statement s = conexion.createStatement(); 
             ResultSet rs = s.executeQuery ("SELECT * FROM `Curso`");
           DefaultTableModel modelo= new DefaultTableModel();
           tablaCursos.setModel(modelo);
           modelo.addColumn("id");
           modelo.addColumn("Curso");
           
             while(rs.next()){
               Object []filas =new Object[2];
               filas[0]=rs.getInt("idCurso");
               filas[1]=rs.getString("nombre");
               modelo.addRow(filas);
             }
             
             
            
            
            
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Lista, Modificar Cursos");
        setPreferredSize(new java.awt.Dimension(550, 290));
        getContentPane().setLayout(null);

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso"
            }
        ));
        tablaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCursos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 222, 280);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(413, 29, 94, 23);

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(413, 63, 94, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/2.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 250));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, -70, 560, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCursosMouseClicked
        // TODO add your handling code here:
        selec=tablaCursos.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tablaCursosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id= tablaCursos.getValueAt(selec, 0).toString();
        System.out.println(id);
        System.out.println(tablaCursos.getValueAt(selec, 1).toString());
          try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
          Statement s = conexion.createStatement(); 
         
          
            int executeUpdate = s.executeUpdate ("UPDATE Curso SET nombre='"+tablaCursos.getValueAt(selec, 1).toString()+"' WHERE idCurso="+id);
       
            if(executeUpdate==1){
                javax.swing.JOptionPane.showMessageDialog(null, "Se Actualizo la informacion");
            }else if(executeUpdate==0){
                javax.swing.JOptionPane.showMessageDialog(null, "Error!! no se puedo ingresar la información");
            }
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(EditarMateria.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
               try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
          Statement s = conexion.createStatement(); 
             ResultSet rs = s.executeQuery ("SELECT * FROM `Curso`");
           DefaultTableModel modelo= new DefaultTableModel();
           tablaCursos.setModel(modelo);
           modelo.addColumn("id");
           modelo.addColumn("Curso");
           
             while(rs.next()){
               Object []filas =new Object[2];
               filas[0]=rs.getInt("idCurso");
               filas[1]=rs.getString("nombre");
               modelo.addRow(filas);
             }
             
             
            
            
            
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
