/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;
import javax.swing.JOptionPane;
/**
 *
 * @author Aaron
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tUsuario = new javax.swing.JTextField();
        bIngresar = new javax.swing.JButton();
        tPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Notas");
        setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 80, 18);

        tUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(tUsuario);
        tUsuario.setBounds(180, 90, 150, 30);

        bIngresar.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(bIngresar);
        bIngresar.setBounds(170, 190, 184, 27);
        getContentPane().add(tPass);
        tPass.setBounds(180, 130, 150, 30);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TEAM BURTON");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 210, 29);

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Constraseña:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(55, 140, 100, 18);

        vSalir.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        vSalir.setText("Salir");
        vSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSalirActionPerformed(evt);
            }
        });
        getContentPane().add(vSalir);
        vSalir.setBounds(170, 240, 184, 27);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/giphy.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-150, 10, 650, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsuarioActionPerformed

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        // TODO add your handling code here:
        String usuario,clave;
        usuario= tUsuario.getText();
        clave= tPass.getText();
        if ("jose".equals(usuario) & "12345".equals(clave)){
            Interfaz me=new Interfaz();
            me.setLocationRelativeTo(null);
            me.setVisible(true);
            this.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null,"Usted ingreso una clave o usuario incorrecto" , "Ingreso incorrecto", JOptionPane.ERROR_MESSAGE);
            tUsuario.setText(null);
            tPass.setText(null);
            tUsuario.requestFocus();
        }
    }//GEN-LAST:event_bIngresarActionPerformed

    private void vSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_vSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField tPass;
    private javax.swing.JTextField tUsuario;
    private javax.swing.JButton vSalir;
    // End of variables declaration//GEN-END:variables
}
