/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import ConexionBD.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aaron
 */
public class Materias extends javax.swing.JInternalFrame {

    /**
     * Creates new form agregarCurso
     */
    public Materias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tnombrec = new javax.swing.JTextField();
        bagregarc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Agregar Curso");
        setPreferredSize(new java.awt.Dimension(430, 280));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(37, 33, 41, 14);
        getContentPane().add(tnombrec);
        tnombrec.setBounds(82, 30, 157, 20);

        bagregarc.setText("Agregar");
        bagregarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarcActionPerformed(evt);
            }
        });
        getContentPane().add(bagregarc);
        bagregarc.setBounds(249, 29, 71, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/4.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 420, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bagregarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarcActionPerformed
        // TODO add your handling code here:
        String nombre;
        nombre= tnombrec.getText();
        
        
           try {
            try
{
Class.forName("com.mysql.jdbc.Driver");
} catch (Exception e)
{
e.printStackTrace();
}
     Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
          Statement s = conexion.createStatement(); 
            int executeUpdate = s.executeUpdate ("INSERT INTO Curso (nombre) VALUES ('"+nombre+"')");
       
            if(executeUpdate==1){
                javax.swing.JOptionPane.showMessageDialog(null, "Se ingreso correctamente el curso: "+nombre);
                
              
            }else if(executeUpdate==0){
                javax.swing.JOptionPane.showMessageDialog(null, "no se logro ingresar");
            }
        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
           tnombrec.setText(null);
      this.setVisible(false);
      
    }//GEN-LAST:event_bagregarcActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagregarc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tnombrec;
    // End of variables declaration//GEN-END:variables
}
