/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.table.DefaultTableModel;

import ConexionBD.Conexion;

/**
 *
 * @author Aaron
 */
public class Notas extends javax.swing.JInternalFrame {
    public ComboBoxModel modelo;
  int selec=-1;
  String iddCurso;
    /**
     * Creates new form ingresarNotas
     */
    
    
    public Notas() {
        initComponents();
        llamarNotas();
    }
    
    public void  llamarNotas(){
        
        try{
           try{
               
                Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e){
                e.printStackTrace();
}
            Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
            Statement s = conexion.createStatement(); 
            ResultSet rs = s.executeQuery ("SELECT * FROM `Curso`");
         
             while(rs.next()){
                 
           
           cbCursos.addItem(rs.getString("nombre")+"-"+rs.getString("idCurso"));
            
             }
             

        s.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbCursos = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        talum = new javax.swing.JTable();
        bingresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Ingresar notas");
        setPreferredSize(new java.awt.Dimension(550, 350));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Curso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel1.setText("Seleciones el curso:");

        jButton1.setText("Estudiantes Matriculados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Refrescar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbCursos, 0, 253, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 31, 397, 85);

        talum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nombre"
            }
        ));
        talum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                talumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(talum);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 122, 410, 330);

        bingresar.setText("Ingresar nota");
        bingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bingresarActionPerformed(evt);
            }
        });
        getContentPane().add(bingresar);
        bingresar.setBounds(420, 130, 120, 30);

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 180, 120, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StringTokenizer st = new StringTokenizer(cbCursos.getItemAt(cbCursos.getSelectedIndex()).toString(),"-"); 
               String nombrecur=st.nextToken();
               String Cursid=st.nextToken();
             //  System.out.println(""+nombrecur+" "+Cursid);
               
               iddCurso=Cursid;
                      try {
            try{
                Class.forName("com.mysql.jdbc.Driver");
            } catch (Exception e)
        {
                    e.printStackTrace();
    }
            Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());
            Statement s = conexion.createStatement(); 
            Statement s1 = conexion.createStatement();
            Statement s2 = conexion.createStatement();
            ResultSet rs = s.executeQuery ("SELECT * FROM nota where Curso_idCurso="+Cursid);
            DefaultTableModel modelo= new DefaultTableModel();
            talum.setModel(modelo);
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre");
            modelo.addColumn("Promedio final");
           
           while(rs.next()){
                 //System.out.println(rs.getString("Alumno_idAlumno"));
                  ResultSet rs1 = s1.executeQuery ("SELECT * FROM Alumno where idAlumno="+rs.getString("Alumno_idAlumno"));
                  
                 while(rs1.next()){
               Object []filas =new Object[3];
               filas[0]=rs1.getInt("idAlumno");
               filas[1]=rs1.getString("nombre");
                ResultSet rs2 = s2.executeQuery ("SELECT * FROM nota WHERE  `Alumno_idAlumno` ="+rs1.getInt("idAlumno")+" AND `Curso_idCurso` ="+Cursid+" LIMIT 0 , 1");
                while(rs2.next()){
                    float p=rs2.getInt("parcial");
                    float f=rs2.getInt("final");
                    float pro=(p+f)/2;
                    filas[2]=pro;
                }
               modelo.addRow(filas);
                 }
                 
            }
            
        s.close();
        s1.close();
        s2.close();
        conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void talumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_talumMouseClicked
        // TODO add your handling code here:
         selec=talum.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_talumMouseClicked

    private void bingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bingresarActionPerformed
        // TODO add your handling code here:
        String id= talum.getValueAt(selec, 0).toString();
        String curso=iddCurso;
        Promedio jingresoPromedio = new Promedio(id, curso);
        jingresoPromedio.setVisible(true);
    }//GEN-LAST:event_bingresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (Exception e)
            {
                e.printStackTrace();
            }
            cbCursos.removeAllItems(); 
            Connection conexion = DriverManager.getConnection ("jdbc:mysql://"+Conexion.getDbserver()+"/"+Conexion.getDbname(),Conexion.getDbuser(), Conexion.getDbpass());

           Statement s = conexion.createStatement(); 
             ResultSet rs = s.executeQuery ("SELECT * FROM `Curso`");
        
             while(rs.next()){
                 
           
           cbCursos.addItem(rs.getString("nombre")+"-"+rs.getString("idCurso"));
            
             }   
            
        s.close();
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bingresar;
    private javax.swing.JComboBox cbCursos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable talum;
    // End of variables declaration//GEN-END:variables
}
